title: Bharath Subramanian
email: your.bhasubramanian247@gmail.com
description: >
  Researcher | Engineer | Builder of intelligent systems that benefit humans.
baseurl: ""
url: "https://bhasub24.github.io"
theme: minima